[package]
name = "acropolis-cargo"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
publish.workspace = true

[dependencies]
acropolis-store.workspace = true
acropolis-fetch.workspace = true
acropolis-toolchain = { path = "../acropolis-toolchain" }
anyhow.workspace = true
serde.workspace = true
futures.workspace = true
flate2.workspace = true
liblzma.workspace = true
toml = "1"
reqwest.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
