[package]
name = "acro-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "acro"
path = "src/main.rs"

[dependencies]
acro-events.workspace = true
acro-oci.workspace = true
acro-store.workspace = true
acro-fetch.workspace = true
acro-build = { path = "../acro-build" }
acro-exec = { path = "../acro-exec" }
anyhow.workspace = true
clap.workspace = true
tokio.workspace = true
serde_json.workspace = true
reqwest.workspace = true
serde.workspace = true
libc.workspace = true
json5.workspace = true
